const data = {
  products: [
    {
      name: 'HEADSET GAMER REDRAGON ZEUS X, RGB, SOM SURROUND 7.1, DRIVERS 53MM, PRETO, H510-RGB',
      category: 'Fone de Ouvido',
      image: '/images/p1.jpg',
      price: 399.0,
      countInStock: 10,
      brand: 'Redragon',
      rating: 4.5,
      numReviews: 7,
      description: 'high quality product',
    },
    {
      name: 'HEADSET GAMER REDRAGON THEMIS 2, DRIVERS 50MM, BRANCO, H220W-N',
      category: 'Fone de Ouvido',
      image: '/images/p2.jpg',
      price: 124.9,
      countInStock: 20,
      brand: 'Redragon',
      rating: 4.2,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      name: 'HEADSET GAMER LOGITECH G733 LIGHTSPEED 7.1 WIRELESS RGB AZUL, 981-000942',
      category: 'Fone de Ouvido',
      image: '/images/p3.jpg',
      price: 1079.9,
      countInStock: 1,
      brand: 'Logitech',
      rating: 4.8,
      numReviews: 3,
      description: 'high quality product',
    },
    {
      name: 'CAIXA DE SOM XIAOMI MI SMART SPEAKER COM GOOGLE ASSISTENTE BRANCO, XM566BRA',
      category: 'Caixa de Som',
      image: '/images/p4.jpg',
      price: 699.9,
      countInStock: 4,
      brand: 'Xiaomi',
      rating: 4.3,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: "CAIXA DE SOM XIAOMI BLUETOOTH 16W A PROVA D'AGUA PRETO, XM567PRE",
      category: 'Caixa de Som',
      image: '/images/p5.jpg',
      price: 449.9,
      countInStock: 5,
      brand: 'Xiaomi',
      rating: 3.9,
      numReviews: 6,
      description: 'high quality product',
    },
    {
      name: 'CAIXA DE SOM GAMER REDRAGON AIR RGB 6W RMS USB PRETO, GS530',
      category: 'Caixa de Som',
      image: '/images/p6.jpg',
      price: 139.9,
      countInStock: 12,
      brand: 'Redragon',
      rating: 4.3,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};

export default data;
